### ISSUE TITLE
Correct copyright licence mistake

### ISSUE THREAD

**Issue by amandasaurus** [technosophos/codewalk-wagi#1]
chapter 3 ( https://github.com/technosophos/codewalk-wagi/tree/ch3-hello-cgi ) added a dependency on `cgi`, which is AGPL licenced code, and yet the LICENSE.txt file ( https://github.com/technosophos/codewalk-wagi/blob/ch3-hello-cgi/LICENSE.txt ) still says MIT licence. The `cgi` dependency makes rust code from this AGPL licenced, not MIT. The README should be updated to fix this, and the LICENSE file updated.

cf. https://github.com/amandasaurus/rust-cgi/issues/17

**Comment by technosophos** [comment]
Fixed. I just changed the entire repo over to AGPLv3 so that it's internally consistent. See commit 67b42aae6c20a4e7535e2ac16378904672c7cfb9, which was merged on all ten branches.
